# Generated by Django 4.2.2 on 2023-06-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val1', models.FloatField()),
                ('val2', models.FloatField()),
                ('val3', models.FloatField()),
                ('val4', models.FloatField()),
            ],
        ),
    ]
